name: DevSync Daily Commit

on:
  schedule:
    - cron: "15 4 * * *"  # Runs daily at 04:15 UTC
  workflow_dispatch:

jobs:
  commit-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update log file by 22f1000123@ds.study.iitm.ac.in
        run: |
          echo "Daily commit at $(date -u)" >> log.txt

      - name: Commit and push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "22f1000123@ds.study.iitm.ac.in"
          git add log.txt
          git commit -m "Daily log update $(date -u)" || echo "No changes to commit"
          git push
